In [55]:
import sklearn
import pandas as pd
from sklearn.model_selection import train_test_split

# Preprocess

In [56]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [57]:
%autoreload 2
from transformers.preprocessing import CountyTransformer, NoTransformer, RealestateTypeTransformer, PriceOutlierRemoval, PriceMedianMultiplierExtractor

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.linear_model import LinearRegression

## Clean input, remove outliers

In [58]:
cleanse_pipe = Pipeline(
    [('group_county', CountyTransformer()),
     ('type', RealestateTypeTransformer()),
     ('z_score_outlier_drop', PriceOutlierRemoval()),
     ('price_median_multiplier', PriceMedianMultiplierExtractor())])
cleaned_data = cleanse_pipe.fit_transform(train_data)

action  estate_type
RENT    APT                 330.000
        BUSINESS            500.000
        COTT_HOUSE          255.650
        GARAGE               70.000
        HOUSE               487.400
        PART_OF_HOUSE       420.000
        TERR_HOUSE          505.645
SALE    APT               63800.000
        BUSINESS           2162.000
        COTT_HOUSE        35000.000
        FARM              44000.000
        GARAGE             5000.000
        HOUSE             67000.000
        PART_OF_HOUSE     89900.000
        TERR_HOUSE       107000.000
Name: Hind, dtype: float64

In [59]:
cleaned_data = cleaned_data.drop(columns=['Tüüp', 'Kuupäev'])

In [60]:
cleaned_data

,id,Tube,Üldpind,Seisukord,Ehitusaasta,Korrus,Korruseid,Maakond,Hind,action,estate_type,year,ad_year,price_median_multiplier
0,586578,3,56.2,Renoveeritud,1967,2,4,harju maakond,34995.00,SALE,APT,13,13,0.548511
1,292379,3,76.9,Uus,2008,2,3,harju maakond,89760.00,SALE,APT,11,11,1.406897
2,864117,3,66.3,Uus,2015,2,6,harju maakond,185000.00,SALE,APT,15,15,2.899687
3,687362,2,46.3,Uus,1990,4,5,tartu maakond,58000.00,SALE,APT,13,13,0.909091
4,497410,1,23.3,Renoveeritud,1930,1,2,tartu maakond,27000.00,SALE,APT,13,13,0.423197
5,974842,2,44.4,Renoveeritud,1980,2,5,harju maakond,67000.00,SALE,APT,15,15,1.050157
6,432344,2,185.0,Uus,2004,1,1,harju maakond,148000.00,SALE,BUSINESS,12,12,68.455134
7,847700,1,34.0,Keskmine,1991,7,9,harju maakond,209.00,RENT,APT,14,14,0.633333
8,490978,4,110.3,Uus,2008,3,6,harju maakond,139000.00,SALE,APT,12,12,2.178683
9,971527,3,65.9,San. remont tehtud,1993,10,12,harju maakond,85000.00,SALE,APT,15,15,1.332288
10,507356,3,84.3,Renoveeritud,1940,2,4,harju maakond,133800.00,SALE,APT,13,13,2.097179
11,600236,3,67.0,Renoveeritud,1988,3,3,viljandi maakond,20900.00,SALE,APT,15,15,0.327586
12,19533,2,47.0,Keskmine,1977,3,5,tartu maakond,127.82,RENT,APT,9,9,0.387333
13,692649,2,39.5,Valmis,1967,1,4,rapla maakond,13700.00,SALE,APT,13,13,0.214734
14,551250,3,53.6,Renoveeritud,1980,2,5,harju maakond,45000.00,SALE,APT,13,13,0.705329
15,343696,4,214.4,Valmis,1981,1,2,järva maakond,72500.00,SALE,HOUSE,12,12,1.082090
16,170650,2,53.0,Uus,2004,4,5,harju maakond,85000.00,SALE,APT,10,10,1.332288
17,937624,2,49.9,Renoveeritud,1931,1,3,harju maakond,550.00,RENT,APT,15,15,1.666667
18,212705,2,75.5,Uus,2007,3,6,harju maakond,127973.00,SALE,APT,11,11,2.005846
19,700733,4,73.5,Renoveeritud,1987,5,9,ida-viru maakond,250.00,RENT,APT,14,14,0.757576
20,819299,3,66.4,Renoveeritud,1977,4,5,harju maakond,69990.00,SALE,APT,14,14,1.097022
21,803775,2,48.1,Uus,2007,5,8,harju maakond,174900.00,SALE,APT,14,14,2.741379
22,225502,5,207.9,Valmis,2006,3,3,viljandi maakond,85900.00,SALE,APT,11,11,1.346395
23,816638,4,77.7,Valmis,1978,3,3,harju maakond,94900.00,SALE,APT,14,14,1.487461
24,112974,2,61.8,Uus,1948,1,2,ida-viru maakond,13101.89,SALE,APT,10,10,0.205359
25,767730,2,40.0,Uus,2005,2,3,pärnu maakond,250.00,RENT,APT,14,14,0.757576
26,23670,4,74.1,Renoveeritud,1978,5,5,harju maakond,82446.03,SALE,APT,9,9,1.292258
27,388280,3,64.1,Renoveeritud,1988,4,5,harju maakond,350.00,RENT,APT,12,12,1.060606
28,371336,2,40.5,Renoveeritud,1930,5,5,harju maakond,400.00,RENT,APT,12,12,1.212121
29,595134,2,49.4,Renoveeritud,1975,9,9,harju maakond,43900.00,SALE,APT,13,13,0.688088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179971,12685,2,39.0,San. remont tehtud,1974,2,3,harju maakond,25245.10,SALE,APT,9,9,0.395691
179972,398159,3,57.8,Keskmine,1972,2,3,valga maakond,5500.00,SALE,APT,12,12,0.086207
179973,750085,3,47.9,Renoveeritud,1965,5,5,tartu maakond,61900.00,SALE,APT,14,14,0.970219
179974,581856,2,53.8,Uus,2006,2,3,tartu maakond,79900.00,SALE,APT,13,13,1.252351
179975,438962,1,27.6,San. remont tehtud,1924,1,2,harju maakond,195.00,RENT,APT,12,12,0.590909
179976,578957,3,71.6,Uus,2015,4,4,harju maakond,122500.00,SALE,APT,13,13,1.920063
179977,746409,1,53.0,Renoveeritud,1924,2,3,harju maakond,400.00,RENT,APT,14,14,1.212121
179978,203882,3,57.9,Uus,2008,3,3,harju maakond,57500.00,SALE,APT,11,11,0.901254
179979,832776,4,98.3,Uus,2015,2,2,tartu maakond,250000.00,SALE,APT,14,14,3.918495
179980,779621,1,37.5,Vajab san. remonti,1987,4,5,ida-viru maakond,20000.00,SALE,APT,14,14,0.313480
179981,500929,3,61.5,Vajab renoveerimist,1982,1,5,ida-viru maakond,2500.00,SALE,APT,13,13,0.039185
179982,508047,3,49.4,Valmis,1976,2,3,harju maakond,15300.00,SALE,APT,13,13,0.239812
179983,581113,2,73.0,Valmis,2008,4,4,harju maakond,121545.00,SALE,APT,13,13,1.905094
179984,789535,3,66.0,Renoveeritud,1979,5,5,harju maakond,73000.00,SALE,APT,14,14,1.144201
179985,44149,2,62.0,Uus,2006,1,3,harju maakond,67107.23,SALE,APT,10,10,1.051837
179986,170104,4,83.1,Uus,2008,3,3,harju maakond,129800.00,SALE,APT,10,10,2.034483
179987,34873,3,102.5,Uus,2006,3,3,pärnu maakond,114401.85,SALE,APT,10,10,1.793132
179988,497435,3,60.0,Uus,2006,4,5,harju maakond,550.00,RENT,APT,13,13,1.666667
179989,748583,3,65.0,Vajab san. remonti,1990,1,5,harju maakond,75000.00,SALE,APT,14,14,1.175549
179990,575064,3,58.0,Valmis,1970,5,5,harju maakond,48000.00,SALE,APT,13,13,0.752351
179991,697067,3,65.8,Renoveeritud,1985,4,6,harju maakond,89000.00,SALE,APT,13,13,1.394984
179992,896829,2,53.6,Renoveeritud,1986,2,9,harju maakond,58500.00,SALE,APT,15,15,0.916928
179993,656029,1,31.9,Renoveeritud,1978,3,5,järva maakond,10990.00,SALE,APT,13,13,0.172257
179994,811939,2,54.0,Uus,2006,5,5,harju maakond,440.00,RENT,APT,14,14,1.333333
179995,329267,2,55.0,Uus,2008,2,5,harju maakond,350.00,RENT,APT,11,11,1.060606
179996,785316,2,49.8,Renoveeritud,1993,1,2,tartu maakond,60800.00,SALE,APT,14,14,0.952978
179997,165397,3,66.8,Uus,1985,9,9,ida-viru maakond,27801.57,SALE,APT,10,10,0.435761
179998,468953,2,42.0,Valmis,1973,3,3,harju maakond,30000.00,SALE,APT,12,12,0.470219
179999,649640,2,39.0,Renoveeritud,1966,4,4,harju maakond,22000.00,SALE,APT,13,13,0.344828
180000,225512,3,67.7,Valmis,1959,3,3,viljandi maakond,33000.00,SALE,APT,11,11,0.517241

In [61]:
data = pd.read_csv("data/traindata.csv")
strat_split = train_test_split

##  Interpret data

In [62]:
price = cleaned_data['price_median_multiplier']
cleaned_data = cleaned_data.drop(columns=['price_median_multiplier'])
cleaned_data = cleaned_data.drop(columns=['Hind'])

In [64]:
cleaned_data
price

0          0.548511
1          1.406897
2          2.899687
3          0.909091
4          0.423197
5          1.050157
6         68.455134
7          0.633333
8          2.178683
9          1.332288
10         2.097179
11         0.327586
12         0.387333
13         0.214734
14         0.705329
15         1.082090
16         1.332288
17         1.666667
18         2.005846
19         0.757576
20         1.097022
21         2.741379
22         1.346395
23         1.487461
24         0.205359
25         0.757576
26         1.292258
27         1.060606
28         1.212121
29         0.688088
            ...
179971     0.395691
179972     0.086207
179973     0.970219
179974     1.252351
179975     0.590909
179976     1.920063
179977     1.212121
179978     0.901254
179979     3.918495
179980     0.313480
179981     0.039185
179982     0.239812
179983     1.905094
179984     1.144201
179985     1.051837
179986     2.034483
179987     1.793132
179988     1.666667
179989     1.175549
179990     0.752351
179991     1.394984
179992     0.916928
179993     0.172257
179994     1.333333
179995     1.060606
179996     0.952978
179997     0.435761
179998     0.470219
179999     0.344828
180000     0.517241
Name: price_median_multiplier, Length: 179772, dtype: float64

In [65]:
cat_list = [['post-USSR constructure',  'Vajab san. remonti','Vajab renoveerimist', 
       'Renoveeritud', 'San. remont tehtud', 'Keskmine', 'Valmis', 'Uus']]

interpret_transformer = ColumnTransformer(
    [('condition', OrdinalEncoder(categories=cat_list), ['Seisukord']),
     ('onehot', OneHotEncoder(), ['action', 'estate_type', 'Maakond'])], sparse_threshold=0, remainder=StandardScaler())

X = interpret_transformer.fit_transform(cleaned_data)

In [66]:
reg = LinearRegression().fit(X, price)

In [67]:
reg.score(X, price)

0.1524724070703446

# Test

In [44]:
test_data = pd.read_csv("data/testData.csv")

In [45]:
cleanse_pipe.transform(test_data)

KeyError: 'Hind'